#스텟 GUI 설정
stat:
  inventory-title: "스텟"                               #창 제목
  inventory-size: 27                                   #창 사이즈
  inventory-placing: 9                                 #GUI 위치
  item: GLASS_PANE                                     #GUI 아이템 타입
  custom-model-data: 2000                              #GUI 아이템 CustomModelData
  name: "스텟"                                          #GUI 아이템 이름
  description: "당신의 능력치를 향상시킬 수 있습니다."       #GUI 아이템 설명

#가방 GUI 설정
backpack:
  inventory-title: "가방"
  inventory-size: 27
  inventory-placing: 10
  item: BUNDLE
  custom-model-data: 2000
  name: "가방"
  description: "가방을 열 수 있습니다."

#공격력 설정
attack-damage:
  inventory-placing: 1
  stat-item: DIAMOND_SWORD
  stat-item-custommodeldata: 1
  stat-name: "공격력"
  max-level: 10                                        #스텟 최대 레벨
  value-per-stat: 0.1                                  #스텟 당 증가 수치

#최대 체력 설정
max-health:
  inventory-placing: 4
  stat-item: TOTEM_OF_UNDYING
  stat-item-custommodeldata: 1
  stat-name: "체력"
  max-level: 5
  value-per-stat: 0.3

#방어력 설정
defense:
  inventory-placing: 7
  stat-item: DIAMOND_CHESTPLATE
  stat-item-custommodeldata: 1
  stat-name: "방어력"
  max-level: 5
  value-per-stat: 0.05

#공격속도 설정
attack-speed:
  inventory-placing: 21
  stat-item: FEATHER
  stat-item-custommodeldata: 1
  stat-name: "공격속도"
  max-level: 5
  value-per-stat: 0.1

#이동속도 설정
movement-speed:
  inventory-placing: 23
  stat-item: GOLDEN_BOOTS
  stat-item-custommodeldata: 1
  stat-name: "이동속도"
  max-level: 3
  value-per-stat: 0.1

#스텟창 배경 아이템 설정
background:
  stat-item: GLASS_PANE
  stat-item-custommodeldata: 1

#초기화 버튼 설정
init-button:
  inventory-placing: 26
  stat-item: BARRIER
  stat-item-custommodeldata: 1
  stat-name: "스텟 초기화"
  description: "모든 스텟을 초기화합니다."

#자동 줍기
use-automatic-pick-up: true

#GUI 접속 시 자동 세팅
automatic-gui-setting:
  stat: true
  backpack: true

#GUI set할 시 설정할 GUI
set-gui-setting:
  stat: true
  backpack: false

#메인바를 제외한 인벤토리 사용 금지
prohibit-inv: true

#인벤토리 사용 금지 시 사용할 아이템
prohibit-item:
  item: GRAY_STAINED_GLASS_PANE
  custom-model-data: 1

#주운 아이템 정보 메시지 표시
item-pickup-message: true