#Caution!! Don't click gui when player's mode is creative. (if you do this, gui's item will be copied)
#inventory-placing은 나머지 기능들과 동시에 변경하지마세요. (변경하셨다면, 변경된 요소 아이템이 하나가 더 복제될 것입니다.)
#이미 변경 하셨을 때에 대한 해결책은 전에 세팅되어있던 아이템 자리에 inventory-placing 값을 변경해주고 리로드한 후 setbackpack 명령어를 입력해주세요.

stat:
  inventory-title: "스텟"
  inventory-size: 27
  inventory-placing: 9
  item: GLASS_PANE
  custom-model-data: 2000
  name: "스텟"
  description: "당신의 능력치를 향상시킬 수 있습니다."

backpack:
  inventory-title: "가방"
  inventory-size: 27
  inventory-placing: 10
  item: BUNDLE
  custom-model-data: 2000
  name: "가방"
  description: "가방을 열 수 있습니다."

attack-damage:
  inventory-placing: 1
  stat-item: DIAMOND_SWORD
  stat-item-custommodeldata: 1
  stat-name: "공격력"
  max-level: 10
  value-per-stat: 0.1

max-health:
  inventory-placing: 4
  stat-item: TOTEM_OF_UNDYING
  stat-item-custommodeldata: 1
  stat-name: "체력"
  max-level: 5
  value-per-stat: 0.3

defense:
  inventory-placing: 7
  stat-item: DIAMOND_CHESTPLATE
  stat-item-custommodeldata: 1
  stat-name: "방어력"
  max-level: 5
  value-per-stat: 0.05

attack-speed:
  inventory-placing: 21
  stat-item: FEATHER
  stat-item-custommodeldata: 1
  stat-name: "공격속도"
  max-level: 5
  value-per-stat: 0.1

movement-speed:
  inventory-placing: 23
  stat-item: GOLDEN_BOOTS
  stat-item-custommodeldata: 1
  stat-name: "이동속도"
  max-level: 3
  value-per-stat: 0.1

background:
  stat-item: GLASS_PANE
  stat-item-custommodeldata: 1

init-button:
  inventory-placing: 26
  stat-item: BARRIER
  stat-item-custommodeldata: 1
  stat-name: "스텟 초기화"
  description: "모든 스텟을 초기화합니다."

use-automatic-pick-up: true

automatic-gui-setting:
  stat: true
  backpack: true

set-gui-setting:
  stat: true
  backpack: false

prohibit-inv: true

prohibit-item:
  item: GRAY_STAINED_GLASS_PANE
  custom-model-data: 1

item-pickup-message: true