name: JunaraPlugin
version: 1.17.1
author: gabjuho
main: com.gabjuho.junaraplugin.Main
api-version: 1.17
commands:
  setStat:
    description: 테스트용 스텟창 세팅
    usage: /<command>
  setBackpack:
    description: 테스트용 가방창 세팅
    usage: /<command>
  setSP:
    description: 스텟포인트를 주는 커맨드
    usage: /<command>
  stat:
    description: 스텟창 띄우기
    usage: /<command>
  backpack:
    description: 가방창 띄우기
    usage: /<command>
  setGUIAll:
    description: 모든 온라인 플레이어에게 stat, backpack gui를 세팅해주는 커맨드
    usage: /<command>
  iniStat:
    description: 스텟을 초기화 해주는 커맨드
    usage: /<command>
  iniStatAll:
    description: 모든 온라인 유저들의 스텟을 초기화 해주는 커맨드
    usage: /<command>