name: JunaraPlugin
version: 1.17.1
author: gabjuho
main: com.gabjuho.junaraplugin.Main
api-version: 1.17
commands:
  setStat:
    description: 테스트용 스텟창 세팅
    usage: /<command>
  setBackpack:
    description: 테스트용 가방창 세팅
    usage: /<command>
  setSP:
    description: 스텟포인트를 주는 커맨드
    usage: /<command>
  iniAttack:
    description: 공격력 초기화
    usage: /<command>
  iniHealth:
    description: 체력 초기화
    usage: /<command>
  iniDefense:
    description: 방어력 초기화
    usage: /<command>
  iniAttackSpeed:
    description: 공격속도 초기화
    usage: /<command>
  iniMovementSpeed:
    description: 이동속도 초기화
    usage: /<command>
  tpWindow:
    description: tp윈도우창 띄우기
    usage: /<command>
  stat:
    description: 스텟창 띄우기
    usage: /<command>
  backpack:
    description: 가방창 띄우기
    usage: /<command>
  setGUIAll:
    description: 모든 온라인 플레이어에게 stat, backpack gui를 세팅해주는 커맨드
    usage: /<command>